name: Test with coverage
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Build with typescript
          npm install
          npm run build
      - name: Generate coverage report
        run: |
          npm i codecov -g
          npm run test
          codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: unittests
          name: codecov-umbrella
